### ISSUE TITLE
A11.5 Caused and issue.

### ISSUE THREAD

**Issue by Lordicon** [nicolas-f/7DTD-leaflet#12]
Please see the below link which is a post on the 7DTD forums.

https://7daystodie.com/forums/showthread.php?14947-Export-discovered-map-to-png&p=260326&viewfull=1#post260326

**Comment by nicolas-f** [comment]
Thanks for report.

It should be fixed now. Please check with your files. I will release the new version if it is ok.

**Comment by Lordicon** [comment]
I may be doing something wrong because I am not getting the fix to work

**Comment by Lordicon** [comment]
Doing everything I can but can not get it to work.

**Comment by nicolas-f** [comment]
Done.
