### ISSUE TITLE
Rendering error with rivers with A11

### ISSUE THREAD

**Issue by Gilthanaz** [nicolas-f/7DTD-leaflet#7]
Hello!

I've noticed that since A11, rivers are rendered partially in black. While not breaking anything, it looks quite ugly :) 

![7d2d_river_rendering_black-issue](https://cloud.githubusercontent.com/assets/11824291/7012214/c370a96e-dcaf-11e4-9bb9-3b2d40bf4269.png)

Kind Regards
- G

**Comment by nicolas-f** [comment]
Hi,

As you can see in this screenshot this problem is in the game:
![capture d ecran 2015-04-11 14 40 02](https://cloud.githubusercontent.com/assets/1382241/7101419/d17bbd5c-e059-11e4-95ad-98b4e2d5482a.png)

**Comment by Gilthanaz** [comment]
Hi!
Thanks for the answer. I've noticed that in the game it also looks off, but it's dark shades and not tint black. However, i think you're right and this issue will be gone if the rivers also render correctly in the game again; Thus i shall go and create a bug thread with the fun pimps :)

KR,
- G
